### ISSUE TITLE
The lab does not work

### ISSUE THREAD

**Issue by ppecomte** [watson-developer-cloud/conversational-insights#2]
Hello , I am testing the lab for a hackaton thta occurs tomorrow July 9th: The deploy phase fails . Can you help ?

**Comment by ppecomte** [comment]
Apparently the reason for failure is that the Personality Insights service is not created automatically

**Comment by germanattanasio** [comment]
I can look at this later today. Will that work?

**Comment by ppecomte** [comment]
With the Service created beforehand with the same name as in the manifest , the deployment is ok. 
However the application does not start automatically. I am unable to start the app succesfully manually

**Comment by ppecomte** [comment]
Yes Thank you for havng a look at it

**Comment by germanattanasio** [comment]
I think `tone-analyzer` is down. I will check tomorrow if we have or not the service up, the rest of the demo should work

**Comment by germanattanasio** [comment]
The service is still down

**Comment by germanattanasio** [comment]
tone analyzer is back in business :+1:
