### ISSUE TITLE
Cert_Untrusted issue

### ISSUE THREAD

**Issue by sanvaibhav** [watson-developer-cloud/conversational-insights#5]
When I execute the app locally after making the changes as per the steps given, I am able to open the page but not able to see the insight.. receives following error

{ [Error: certificate not trusted] code: 'CERT_UNTRUSTED' }

How to fix this?

Thanks
Vaibhav

**Comment by germanattanasio** [comment]
HI @sanvaibhav, I think the problem you have is not related to the sample, I can run it without issues. Looks like you have a issue with the SSL connection.
Watson uses SHA1 by GeoTrust.

**Comment by sanvaibhav** [comment]
Thanks for the reply...

I identified and fixed the problem which was posted on one of the forum... that was having a problem .cfingnore file which suppose to be in the utf-8 encoding ... which was encoded to others.. that's the reason..

solution... open the file in notepad and save as with utf-8 encoding and... problem gone !!!!

Thanks
Vaibhav

**Comment by germanattanasio** [comment]
Cool, I'm closing the bug then
